version: "3.4"
services:
   frontend:
      image: jenkins/jenkins:lts
      ports:
        - 8080:8080
        - 50000:50000
      networks:
         - jenkins_network
      volumes:
        - jenkins_vol:/var/jenkins_home
volumes:
  jenkins_vol:
    driver: local
networks:
  jenkins_network:
    driver: bridge
